set(CC_PLATFORM_OPENHARMONY 14)
add_definitions(-DCC_PLATFORM_OPENHARMONY=${CC_PLATFORM_OPENHARMONY})

set(CC_PLATFORM ${CC_PLATFORM_OPENHARMONY})
add_definitions(-DOPENHARMONY=${CC_PLATFORM_OPENHARMONY})
add_definitions(-DCC_PLATFORM=${CC_PLATFORM})
set(CMAKE_CXX_FLAGS "-fvisibility=hidden -fvisibility-inlines-hidden ${CMAKE_CXX_FLAGS}")
if("${OHOS_ARCH}" STREQUAL "armeabi-v7a")
    set(CMAKE_CXX_FLAGS "-march=armv7a ${CMAKE_CXX_FLAGS}")
endif()

MESSAGE(STATUS "platform: ${CMAKE_SYSTEM_NAME}")

################################# cc_set_if_undefined ###################################
macro(cc_set_if_undefined varname value)
    if(NOT DEFINED ${varname})
        set(${varname} ${value})
    endif()
endmacro()


################################# cocos_source_files ###################################
macro(cocos_source_files)
    set(list_var "${ARGN}")
    set(TWAE ON)
    set(ACCEPT_MN OFF)
    set(MODULE_NAME "COCOS")
    set(NO_UBUILD OFF)
    foreach(src IN LISTS list_var)
        if(ACCEPT_MN)
            set(MODULE_NAME "${src}")
            set(ACCEPT_MN OFF)
        elseif("NO_WERROR" STREQUAL "${src}")
            set(TWAE OFF)
        elseif("MODULE" STREQUAL "${src}")
            set(ACCEPT_MN ON)
        elseif("NO_UBUILD" STREQUAL "${src}")
            set(NO_UBUILD ON)
        else()
            if(IS_ABSOLUTE "${src}")
                set(fp "${src}")
            else()
                set(fp "${CWD}/${src}")
            endif()
            get_source_file_property(IS_GENERATED ${fp} GENERATED)
            if(EXISTS ${fp} OR ${IS_GENERATED})
                if("${fp}" MATCHES "\\.(cpp|mm|c|m)\$" AND TWAE)
                     set_source_files_properties("${fp}" PROPERTIES
                         COMPILE_FLAGS "${WERROR_FLAGS}"
                     )
                endif()
                if("${fp}" MATCHES "\\.(cpp|mm|c|m)\$" AND NO_UBUILD)
                    set_source_files_properties("${fp}" PROPERTIES
                         SKIP_UNITY_BUILD_INCLUSION ON
                    )
                endif()
                list(APPEND ${MODULE_NAME}_SOURCE_LIST "${fp}")
            else()
                message(FATAL_ERROR "Cocos souce file not exists: \"${src}\", is generated ${IS_GENERATED}")
            endif()
            set(TWAE ON)
            set(NO_UBUILD OFF)
        endif()
    endforeach()
endmacro()

if(NOT DEFINED NODE_EXECUTABLE)
    if(DEFINED EDITOR_NODEJS)
        set(NODE_EXECUTABLE ${EDITOR_NODEJS})
    elseif(DEFINED ENV{NODE_EXECUTABLE})
        set(NODE_EXECUTABLE $ENV{NODE_EXECUTABLE})
        message(STATUS "set NODE_EXECUTABLE by env")
    else() 
        find_program(NODE_EXECUTABLE NAMES node)
    endif()
endif()
if(NOT DEFINED TSC_EXECUTABLE)
    find_program(TSC_EXECUTABLE NAMES tsc)
endif()
if(NOT DEFINED CCACHE_EXECUTABLE)
    find_program(CCACHE_EXECUTABLE NAMES ccache)
endif()
